name: Kubernetes 1.28.15 Images Syncer

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup skopeo
      run: sudo apt-get update && sudo apt-get -y install skopeo
    - name: Copy images
      run: bash skopeo.sh
      env: 
        IMAGES_LIST_FILE: kubernetes/v1.28.15/kubernetes.txt
        REGISTRY: swr.cn-east-5.myhuaweicloud.com
        REPOSITORY: tsiongchi
        USERNAME: ${{ vars.HUAWEI_USERNAME }}
        TOKEN: ${{ secrets.HUAWEI_TOKEN }}