name: KubeSphere V4.1.2 Images Syncer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup skopeo
      run: sudo apt-get update && sudo apt-get -y install skopeo
    - name: Copy images
      run: bash skopeo.sh
      env: 
        IMAGES_LIST_FILE: kubesphere/v4.1.2/kubesphere-4.1.2.yml
        HUAWEI_TOKEN: ${{ secrets.HUAWEI_TOKEN }}
        ALIYUN_TOKEN: ${{ secrets.ALIYUN_TOKEN }}
        QUAYIO_TOKEN: ${{ secrets.QUAYIO_TOKEN }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        EARTH_TOKEN: ${{ secrets.EARTH_TOKEN }}