name: Docker PostGIS CI

on:
  workflow_dispatch:
  schedule:
    - cron: '15 15 * * 1'

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    strategy:
      matrix:
        postgres: [13, 14, 15, 16, 17]
        postgis: ['3.5']
        variant: [default, alpine]
        include:
          - postgres: 16
            postgis: master
            variant: default
          - postgres: 17
            postgis: master
            variant: default

    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }} variant ${{ matrix.variant }}
    runs-on: ubuntu-24.04
    continue-on-error: ${{ matrix.postgis == 'master' }}
    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}
      VARIANT: ${{ matrix.variant }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: postgis source
        run: git clone https://github.com/postgis/docker-postgis.git

      - name: Setup skopeo
        run: sudo apt-get update && sudo apt-get -y install skopeo

      - name: Login to TCR
        uses: docker/login-action@v3
        with:
          registry: swr.cn-east-5.myhuaweicloud.com
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_ACCESS_TOKEN }}

      - name: Login to Aliyun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_ACCESS_TOKEN }}

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ACCESS_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:buildx-stable-1

      - name: Build docker image for ${{ env.VERSION }} ${{ env.VARIANT }}
        env:
          HUAWEI_TOKEN: ${{ secrets.HUAWEI_TOKEN }}
        run: |
          skopeo login -u $(echo ${HUAWEI_TOKEN} | awk -F ':' '{print $1}') -p $(echo ${HUAWEI_TOKEN} | awk -F ':' '{print $2}') swr.cn-east-5.myhuaweicloud.com
          rm -rf docker-postgis/Makefile
          grep -rl "LABEL" docker-postgis | xargs sed -i 's#org.opencontainers.image.source="https://github.com/postgis/docker-postgis"#org.opencontainers.image.source="https://github.com/athlonreg/docker"#g'
          cp postgis.Makefile docker-postgis/Makefile
          cd docker-postgis
          make test
